### ISSUE TITLE
Question about your comparison with Hermes

### ISSUE THREAD

**Issue by mileswyn** [ZhangxinruBIT/MoME#1]
Thank you for your appreciative work~
When your paper was early accepted by MICCAI 2024, the comparison method "Hermes" had not yet been open-sourced.
So I wonder where the comparison results of "Hermes" came from.
Was it from the author of "Hermes" or your reproduction?
Since your work is based on nnUNet framework and Hermes' code is based on different.

**Comment by ZhangxinruBIT** [comment]
Thanks. I followed the idea of "Context Prior" from Hermes but applied it to the bottleneck of the nnUNet framework. For my implementation, I used one-hot encoding for modality information. However, task information cannot be considered prior knowledge. Specifically, in the brain lesion segmentation task, different patients may have different lesion types, so lesion type is not considered prior information and cannot be embedded into the bottleneck.
